name: GitHub Activity Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Actor: $GITHUB_ACTOR"
          echo "GH_PAT is set: ${{ secrets.GH_PAT != '' }}"
      
      - name: Run Report Script
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GH_PAT: ${{ secrets.GH_PAT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MONTHLY_CODE_CHANGES_GOAL: ${{ vars.MONTHLY_CODE_CHANGES_GOAL }}
          MONTHLY_PR_CREATION_GOAL: ${{ vars.MONTHLY_PR_CREATION_GOAL }}
          MONTHLY_PR_MERGE_GOAL: ${{ vars.MONTHLY_PR_MERGE_GOAL }}
          USERNAME: ${{ vars.USERNAME }}
