name: GitHub Activity Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions: read-all

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Actor: $GITHUB_ACTOR"
          echo "Token: ${{ github.token != '' }}"
      
      - name: Run Report Script
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MONTHLY_CODE_CHANGES_GOAL: 100
          MONTHLY_PR_CREATION_GOAL: 10
          MONTHLY_PR_MERGE_GOAL: 5
          USERNAME: ebijun1007
