name: GitHub Activity Report

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, closed ]
  workflow_dispatch:

permissions:
  contents: read

env:
  MONTHLY_CODE_CHANGES_GOAL: ${{ vars.MONTHLY_CODE_CHANGES_GOAL }}
  MONTHLY_PR_CREATION_GOAL: ${{ vars.MONTHLY_PR_CREATION_GOAL }}
  MONTHLY_PR_MERGE_GOAL: ${{ vars.MONTHLY_PR_MERGE_GOAL }}
  USERNAME: ${{ vars.USERNAME }}

jobs:
  report:
    if: github.actor == vars.USERNAME
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
      
      - name: Install dependencies
        run: sudo apt-get install -y jq bc
      
      - name: Generate Activity Report
        run: |
          chmod +x ./scripts/generate_report.sh
          GITHUB_TOKEN=${{ secrets.GITHUB_PAT }} ./scripts/generate_report.sh
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DEBUG: ${{ vars.DEBUG || 'false' }}
