name: GitHub Activity Report

on:
  pull_request:
    types: [ opened, closed ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONTHLY_CODE_CHANGES_GOAL: '100'
      MONTHLY_PR_CREATION_GOAL: '10'
      MONTHLY_PR_MERGE_GOAL: '5'
      USERNAME: 'ebijun1007'
      DEBUG: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "::group::Environment Setup"
          echo "Setting up debug mode..."
          set -x
          
          echo "Checking GitHub token..."
          if [ -n "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is set"
          else
            echo "Error: GH_PAT is not set"
            exit 1
          fi
          
          echo "Checking environment variables..."
          env | grep -E "MONTHLY_|USERNAME|SLACK_|GITHUB_" || true
          
          echo "Checking GitHub CLI..."
          gh --version || echo "GitHub CLI not found"
          gh auth status || echo "GitHub CLI not authenticated"
          
          echo "Checking script permissions..."
          ls -la ./scripts/
          chmod +x ./scripts/generate_report.sh
          echo "::endgroup::"
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt-get update \
          && sudo apt-get install gh -y
      
      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
      
      - name: Install dependencies
        run: sudo apt-get install -y jq bc
      
      - name: Generate Activity Report
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
