name: GitHub Activity Report

on:
  schedule:
    - cron: '0 9 * * *'
  pull_request:
    types: [ opened, closed ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONTHLY_CODE_CHANGES_GOAL: ${{ vars.MONTHLY_CODE_CHANGES_GOAL || '100' }}
      MONTHLY_PR_CREATION_GOAL: ${{ vars.MONTHLY_PR_CREATION_GOAL || '10' }}
      MONTHLY_PR_MERGE_GOAL: ${{ vars.MONTHLY_PR_MERGE_GOAL || '5' }}
      USERNAME: ${{ vars.USERNAME || 'ebijun1007' }}
      DEBUG: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          {
            echo "::group::Environment Setup"
            echo "Setting up debug mode..."
            echo "Working Directory: $(pwd)"
            echo "Repository: $GITHUB_REPOSITORY"
            echo "Event: $GITHUB_EVENT_NAME"
            echo "Actor: $GITHUB_ACTOR"
            echo "Ref: $GITHUB_REF"
            echo "SHA: $GITHUB_SHA"
            echo "Token Status: $([ -n "$GH_PAT" ] && echo "Set" || echo "Not Set")"
            echo "Webhook Status: $([ -n "$SLACK_WEBHOOK_URL" ] && echo "Set" || echo "Not Set")"
            echo "Environment Variables:"
            env | grep -E "MONTHLY_|USERNAME|SLACK_|GITHUB_|GH_" || true
            echo "Script Permissions:"
            ls -la ./scripts/
            echo "GitHub CLI Version:"
            gh --version || echo "GitHub CLI not found"
            echo "GitHub Auth Status:"
            gh auth status || echo "GitHub CLI not authenticated"
            echo "::endgroup::"
          } 2>&1 | tee debug.log
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt-get update \
          && sudo apt-get install gh -y
      
      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
      
      - name: Install dependencies
        run: sudo apt-get install -y jq bc
      
      - name: Generate Activity Report
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
