name: GitHub Activity Report

on:
  pull_request:
    types: [ opened, closed ]
  workflow_dispatch:

permissions: write-all

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONTHLY_CODE_CHANGES_GOAL: ${{ vars.MONTHLY_CODE_CHANGES_GOAL }}
      MONTHLY_PR_CREATION_GOAL: ${{ vars.MONTHLY_PR_CREATION_GOAL }}
      MONTHLY_PR_MERGE_GOAL: ${{ vars.MONTHLY_PR_MERGE_GOAL }}
      USERNAME: ${{ vars.USERNAME }}
      DEBUG: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Basic Setup
        run: |
          echo "Setting up environment..."
          ls -la
          chmod +x ./scripts/generate_report.sh
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt-get update \
          && sudo apt-get install gh -y
      
      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
      
      - name: Install dependencies
        run: sudo apt-get install -y jq bc
      
      - name: Generate Activity Report
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
