name: GitHub Activity Report

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, closed ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: read
  organization-projects: read
  packages: read
  deployments: read

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      MONTHLY_CODE_CHANGES_GOAL: ${{ vars.MONTHLY_CODE_CHANGES_GOAL }}
      MONTHLY_PR_CREATION_GOAL: ${{ vars.MONTHLY_PR_CREATION_GOAL }}
      MONTHLY_PR_MERGE_GOAL: ${{ vars.MONTHLY_PR_MERGE_GOAL }}
      USERNAME: ${{ vars.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DEBUG: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "::group::Environment Check"
          echo "Required Variables:"
          echo "- MONTHLY_CODE_CHANGES_GOAL exists: ${{ vars.MONTHLY_CODE_CHANGES_GOAL != '' }}"
          echo "- MONTHLY_PR_CREATION_GOAL exists: ${{ vars.MONTHLY_PR_CREATION_GOAL != '' }}"
          echo "- MONTHLY_PR_MERGE_GOAL exists: ${{ vars.MONTHLY_PR_MERGE_GOAL != '' }}"
          echo "Required Secrets:"
          echo "- GH_PAT exists: ${{ secrets.GH_PAT != '' }}"
          echo "- SLACK_WEBHOOK_URL exists: ${{ secrets.SLACK_WEBHOOK_URL != '' }}"
          echo "::endgroup::"
          
          echo "::group::Repository Contents"
          ls -la
          echo "::endgroup::"
          
          echo "::group::Script Check"
          if [ -f "./scripts/generate_report.sh" ]; then
            echo "Script exists"
            ls -la ./scripts/generate_report.sh
          else
            echo "Error: Script not found"
            exit 1
          fi
          echo "::endgroup::"
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt-get update \
          && sudo apt-get install gh -y
      
      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
      
      - name: Install dependencies
        run: sudo apt-get install -y jq bc
      
      - name: Generate Activity Report
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
