name: GitHub Activity Report

on:
 schedule:
   - cron: '0 21,22,23,0,1,2,3,4,5,6,7,8,9,10,11 * * *'  # JST 6-20
 push:
   branches: [ main, master ]
 pull_request:
   types: [ opened, closed ]
 workflow_dispatch:

env:
  MONTHLY_CODE_CHANGES_GOAL: ${{ vars.MONTHLY_CODE_CHANGES_GOAL }}
  MONTHLY_PR_CREATION_GOAL: ${{ vars.MONTHLY_PR_CREATION_GOAL }}
  MONTHLY_PR_MERGE_GOAL: ${{ vars.MONTHLY_PR_MERGE_GOAL }}
  USERNAME: ${{ vars.USERNAME }}

jobs:
  report:
    # 個人の活動のみを対象とする
    if: github.actor == vars.USERNAME
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq bc
      
      - name: Generate Activity Report
        run: |
          chmod +x ./scripts/generate_report.sh
          ./scripts/generate_report.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DEBUG: ${{ vars.DEBUG || 'false' }}
